// Script:    TestePilhaDeCartas.script
// Autor:     Eric Grinstein
//			  Jordana Mecler
//			  Leonardo Wajnsztok
// Propósito: Testar o módulo 
//			  Baralho de Cartas.
//

== Criar baralho numero 0
=criar 0 0

== Pop Ás de copas, baralho vazio.
=pop 0 'c' 1 1

== Preencher baralho com 1 naipe
=preencher 0 1 0

== Pop K de copas, ok
=pop 0 'c' 13 0

== Pop Q de copas, ok
=pop 0 'c' 12 0
 
== Embaralhar baralho 0
=embaralhar 0 0

== Pop J de paus, (provavelmente, a carta será errada)
=pop 0 'p' 11 0
=recuperar

== Criar baralho no slot 1
=criar    1 0

== Preencher baralho 1 com 3 naipes
=preencher 1 3 0

== Destruir baralho 1
=destruir 1 0
 
== Destruir baralho 0
=destruir 0 0

// fim
